name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v3
    - name: Cache build
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache
          build
        key: ${{ runner.os }}-build-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-build-
    - name: Install dependencies
      run: sudo apt-get install -y ${{ matrix.compiler }} libx11-dev libxft-dev pkg-config
    - name: Set PKG_CONFIG_PATH
      run: |
        echo "PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
    - name: Compile
      run: make CC=${{ matrix.compiler }}
    - name: Run tests
      run: make check
    - name: Run distcheck
      run: make distcheck

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y cppcheck
    - name: Run cppcheck
      run: cppcheck --enable=all .
